---
defaults: &defaults
  oracle_username: cloud.admin
  oracle_password: slacK@5FoLDing
  oracle_domain: gse00000535
  oracle_compute_api: https://api-z11.compute.em2.oraclecloud.com/
  oracle_storage_api: https://gse00000535.storage.oraclecloud.com/v1/Storage-gse00000535

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults